### PR TITLE
Static site updates redux

### PR DESCRIPTION
**Pull request by Katee**
This contains the same changes as https://github.com/google/cloudprober/pull/283 without switching to `pygmentsUseClasses`.

### CODE REVIEW

**Comment by Katee** [comment]
Actually this will still cause highlighting issues.

**Comment by Katee** [comment]
Removing highlightjs fixed the issue. See https://katee.github.io/cloudprober/ for a demo.

**Comment by manugarg** [comment]
Thanks for chasing this, Katee. 

I think for Chroma, we need to generate a syntax.css and include it in the generated pages. Otherwise Go's syntax is not recognized at all. 

See from: https://katee.github.io/cloudprober/how-to/external-probe/
Screen Shot 2019-09-21 at 1 52 12 AM


I tried a few styles, I think pygments looks best:
hugo gen chromastyles --style=pygments > syntax.css
(I modified the generated file for testing.)

We'll need to include that file in the static directory (I think at static/stylesheets/syntax.css, but not sure) and change the theme's [head](https://github.com/google/cloudprober/blob/master/docs/themes/hugo-material-docs/layouts/partials/head.html) to include this css.

Can you please try doing that. Thanks again!

**Comment by Katee** [comment]
I added the pygments chroma scheme and made some minor modifications to more closely match what you had (59f0f7c2e77e92d1a1e360b1493eb51ce73d5054).

example of the difference:
orig:
orig

default chroma pygments:
default-pygments

modified to match original:
overwrite

**Comment by manugarg** [comment]
Awesome. Thank you, Katee.

Pushed the changes to the live site.

**Pull request merged**
